apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: kind-server
  name: kind-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: kind-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: kind-server
    spec:
      containers:
        - image: 'alpine:3.12.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - echo
                - ok
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          name: kind-server
          readinessProbe:
            exec:
              command:
                - echo
                - ok
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kindroot
      serviceAccountName: kindroot
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange