apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: kind-server
  name: kind-server
  namespace: ok-kind-test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: kind-server
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: kind-server
        name: kind-server
    spec:
      containers:
      - image: 'ubuntu:18.04'
        name: kind-server
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "su -; apt update -y && apt upgrade -y; apt install curl; curl --version; sleep 40; curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-$(uname)-amd64; chmod +x ./kind; mv ./kind /$(PATH)/kind; curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl; chmod +x ./kubectl; sudo mv ./kubectl /usr/local/bin/kubectl; kubectl version --client; kind create cluster"]
        livenessProbe:
          exec:
            command:
              - sleep
              - "3600"
          failureThreshold: 3
          initialDelaySeconds: 180
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          requests:
            memory: 512Mi
        dnsPolicy: ClusterFirst
        serviceAccount: kindroot
        serviceAccountName: kindroot
  triggers:
    - type: ConfigChange