kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: ok-kind-test
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowedCapabilities:
- SYS_ADMIN
- SYS_RESOURCE
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- oleksandr_krainiuk@epam.com